repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks # Hinders git commit with too large files.
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: check-json
    - id: check-yaml

-   repo: https://github.com/ambv/black # Auto formats code.
    rev: 23.7.0
    hooks:
    - id: black
      language_version: python3

- repo: https://github.com/charliermarsh/ruff-pre-commit # Checks for pep257 compliance.
  rev: 'v0.0.287'
  hooks:
    - id: ruff
