name: graph_pkg_env
channels:
  - conda-forge
  - pytorch
  - pyg
  - anaconda
  - milagraph
dependencies:
  - python==3.9.17
  - pytorch
  - torchdrug==0.2.1
  - aiohttp
  - colorlog
  - pytorch-scatter
  - pytorch-cluster
  - requests
  - pip
  - pandas
  - tqdm
  - wandb
  - python-dotenv
  - torchmetrics
  - pytorch-lightning
  - hydra-core
  - jsonlines
  - scipy
  - scikit-learn
  - seaborn

  - pip:
    - -r requirements.txt