name: graph_pkg_new
channels:
  - conda-forge
  - pytorch
  - pyg
  - anaconda
  - milagraph
dependencies:
  - python==3.9.17
  - pytorch==1.12.0
  - torchdrug
  - aiohttp
  - colorlog
  - pytorch-scatter
  - pytorch-cluster
  - requests
  - pip
  - pandas
  - tqdm
  - wandb
  - python-dotenv
  - torchmetrics
  - pytorch-lightning
  - hydra-core
  - pip:
    - -r requirements.txt