name: graph_pkg_env
channels:
  - conda-forge
  - pytorch
  - pyg
  - anaconda
dependencies:
  - python==3.7.16
  - pytorch==1.10.0
  - aiohttp
  - colorlog
  - pytorch-scatter
  - pytorch-cluster
  - requests
  - pip
  - pandas
  - tqdm
  - wandb
  - python-dotenv
  - pip:
    - -r requirements.txt