# @package _global_

run_name: 'NO_NAME'
wandb: False
lr: 0.001
l2_reg: False
batch_sizes: {"train": 128,"val": 1000, "test": 10000}
group_val: False
max_train_triplets: 120 #if group_val="drug_few_shot", this value determines amount of triplets to be included in train
n_drugs_per_fold: 8
n_cell_lines_per_fold: 10


n_splits: 5
seed: 43
remove_old_checkpoints: True
task: 'reg' #clf (does not work for css)

dataset:  
  name: 'oneil_almanac_het' # deepdds_original, oneil_legacy, oneil_almanac
  target: 'zip_mean' # zip_max, css, loewe (legacy)
  use_node_features: False
  use_edge_features: False  
  drug_representation: morgan # morgan, onehot
  modalities: False # All, Gene, Side Effect, Disease, Pharmacologic Class
  edge_weights: False # continous, discrete, False

checkpoint_callback:
  mode: 'min'
  filename: '{epoch:02d}-{val_mse:.4f}'
  monitor: 'val_mse'
  save_top_k: 1

trainer:  
  check_val_every_n_epoch: 1
  max_epochs: 100
  enable_checkpointing: True
  enable_progress_bar: True
  fast_dev_run: False












