# @package _global_
model:
  prediction_head: mlp
  ph_kwargs:
      dataset: ''
      use_mono_response: False
      custom_lr_setup:
        value: True
        lr_ph_cell_mlp: 0.001
        lr_ph_global_mlp: 0.0001
