# DONT CHANGE THIS FILE
defaults:
  - _self_
  - model: deepdds # override model by writing model=rescal or model=hybridmodel as command line argument to main.py

run_name: 'NO_NAME'
wandb: False
lr: 0.001
batch_sizes: {"train": 128,"val": 1000, "test": 10000}
group_val: False

n_splits: 5
seed: 43
remove_old_checkpoints: True
task: 'reg' #clf (does not work for css)

dataset:  
  name: 'oneil' # deepdds_original, oneil_legacy
  target: 'zip_mean' # zip_max, css, loewe (legacy)

checkpoint_callback:
  mode: 'max'
  filename: '{epoch:02d}-{val_auroc:.4f}'
  monitor: 'val_auroc'
  save_top_k: 1

trainer:  
  check_val_every_n_epoch: 1
  max_epochs: 100
  enable_checkpointing: True
  enable_progress_bar: True
  limit_test_batches: 1000
  fast_dev_run: False












